version: '2'
services:
  web:
    build: ./web
    #image: generydey/jws:web
    image: jws:web
    ports: 
      - "80:80"
    links:
      - db:db
    depends_on:
      - "db"
  db:
    #image: generydey/jws:db
    image: jws:db
    build: ./mysql
